### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by dantman** [Saeris/apollo-server-vercel#2]
I tried using this to expose our GraphQL API on our Vercel based demos. But it doesn't appear this actually works, because Headers is not imported from anywhere.

```
ReferenceError: Headers is not defined
    at ApolloServer.createHandler (.../node_modules/@saeris/apollo-server-vercel/dist-src/ApolloServer.js:25:25)
    at Object.<anonymous> (.../api/graphql.ts:15:23)
```

**Comment by Saeris** [comment]
Yeah so this is still very much in development and I haven't had the time to get it working properly yet. Please do not use it, it definitely will not work.

**Comment by Saeris** [comment]
@dantman might want to give this another try! Did some more work over the weekend and got all the official Apollo integration tests working. Let me know if you encounter further problems!

**Comment by Saeris** [comment]
Alright so I guess this is still an issue and I'm working on a fix. Thought I had it working since I was able to use the library in a demo nextjs project, but I'm running into this same problem while trying to add an example api to this repo. Adding `node-fetch` to polyfill the dom Headers api should be part of the solution, but at this moment I'm still having some issues. I'll update when I've got a fix!
